### ISSUE TITLE
core20 build failing

### ISSUE THREAD

**Issue by MarcusTomlinson** [canonical/flutter-snap#43]
The snap started failing automatic review on core20 with the following error today:

`package contains external symlinks: usr/lib/x86_64-linux-gnu/libdbus-1.so lint-snap-v2_external_symlinks `

Subsequently, this results in libdbus linker errors when using the snap too.

**Comment by MarcusTomlinson** [comment]
Gotten further with this (https://github.com/canonical/flutter-snap/commit/ced6e465a407d414a83a95e10ed03cafa58f1086 together with https://github.com/canonical/flutter-snap/tree/core20). But now I get:

```
[  +90 ms] Building Linux application... (completed in 8.8s)
[+1734 ms] Error waiting for a debug connection: The log reader stopped unexpectedly.
[   +2 ms] Error launching application on Linux.
[   +2 ms] "flutter run" took 10,914ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[  +59 ms] ensureAnalyticsSent: 52ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

No other errors in the log above :/
