### ISSUE TITLE
snapcraft fails with CMake Error

### ISSUE THREAD

**Issue by drexhacker** [canonical/flutter-snap#47]
When i run ```snapcraft``` to build the snap i get this error;
```
Launching a VM.
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
The flutter plugin is currently in beta, its API may break. Use at your own risk.
snapd is not logged in, snap install commands will use sudo
snap "core18" has no updates available
Skipping pull flutter-extension (already ran)
Skipping pull gnome-3-28-extension (already ran)
Updating pull step for xifair-admin (source changed)
+ snapcraftctl pull
Skipping build flutter-extension (already ran)
Skipping build gnome-3-28-extension (already ran)
Building xifair-admin 
+ snapcraftctl build
flutter pub get
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Running "flutter pub get" in build...                               5.9s
flutter build linux --release -v -t lib/main.dart
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
[ +120 ms] executing: uname -m
[  +61 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +15 ms] executing: [/root/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +11 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] db930ba32f320cb0ca53595a2df0e4a9fe15101d
[   +1 ms] executing: [/root/snap/flutter/common/flutter/] git tag --points-at db930ba32f320cb0ca53595a2df0e4a9fe15101d
[  +26 ms] Exit code 0 from: git tag --points-at db930ba32f320cb0ca53595a2df0e4a9fe15101d
[   +3 ms] executing: [/root/snap/flutter/common/flutter/] git describe --match *.*.* --long --tags db930ba32f320cb0ca53595a2df0e4a9fe15101d
[  +67 ms] Exit code 0 from: git describe --match *.*.* --long --tags db930ba32f320cb0ca53595a2df0e4a9fe15101d
[        ] 2.3.0-16.0.pre-366-gdb930ba32f
[  +13 ms] executing: [/root/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/root/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +174 ms] Unable to locate an Android SDK.
[  +10 ms] executing: [/root/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +157 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +167 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[ +256 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +190 ms] Skipping pub get: version match.
[ +103 ms] Found plugin dart_vlc at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.0.7/
[  +14 ms] Found plugin disk_space at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/disk_space-0.1.1/
[  +16 ms] Found plugin file_picker at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-3.0.2+2/
[   +9 ms] Found plugin file_selector at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector-0.8.2/
[   +2 ms] Found plugin file_selector_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_linux-0.0.2/
[   +3 ms] Found plugin file_selector_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_macos-0.0.4/
[   +8 ms] Found plugin file_selector_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_web-0.8.1/
[   +2 ms] Found plugin file_selector_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_windows-0.0.2/
[   +7 ms] Found plugin firexcode at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firexcode-1.0.5/
[  +18 ms] Found plugin flutter_plugin_android_lifecycle at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.1/
[  +29 ms] Found plugin image_editor_pro at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_editor_pro-1.1.8/
[   +7 ms] Found plugin image_picker at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.7.5/
[   +4 ms] Found plugin image_picker_for_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.0.0/
[  +20 ms] Found plugin package_info_plus at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus-1.0.1/
[   +3 ms] Found plugin package_info_plus_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus_macos-1.1.1/
[   +4 ms] Found plugin package_info_plus_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus_web-1.0.1/
[  +10 ms] Found plugin path_provider at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.2/
[   +2 ms] Found plugin path_provider_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +2 ms] Found plugin path_provider_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +3 ms] Found plugin path_provider_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.1/
[   +3 ms] Found plugin permission_handler at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/
[  +13 ms] Found plugin share_plus at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus-2.1.2/
[   +3 ms] Found plugin share_plus_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus_macos-2.0.2/
[   +3 ms] Found plugin share_plus_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus_web-2.0.4/
[   +3 ms] Found plugin shared_preferences at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.5/
[   +3 ms] Found plugin shared_preferences_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
[   +2 ms] Found plugin shared_preferences_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
[   +5 ms] Found plugin shared_preferences_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
[   +2 ms] Found plugin shared_preferences_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
[  +14 ms] Found plugin url_launcher at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.4/
[   +2 ms] Found plugin url_launcher_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.0/
[   +1 ms] Found plugin url_launcher_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.0/
[   +2 ms] Found plugin url_launcher_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.0/
[   +1 ms] Found plugin url_launcher_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.0/
[   +3 ms] Found plugin video_player at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-2.1.1/
[   +3 ms] Found plugin video_player_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_player_web-2.0.0/
[   +2 ms] Found plugin wakelock at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.5.2/
[   +2 ms] Found plugin wakelock_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_macos-0.1.0+1/
[   +3 ms] Found plugin wakelock_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_web-0.2.0+1/
[ +602 ms] Found plugin dart_vlc at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/dart_vlc-0.0.7/
[   +2 ms] Found plugin disk_space at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/disk_space-0.1.1/
[   +9 ms] Found plugin file_picker at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-3.0.2+2/
[   +2 ms] Found plugin file_selector at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector-0.8.2/
[   +1 ms] Found plugin file_selector_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_linux-0.0.2/
[   +1 ms] Found plugin file_selector_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_macos-0.0.4/
[   +2 ms] Found plugin file_selector_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_web-0.8.1/
[   +1 ms] Found plugin file_selector_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_windows-0.0.2/
[   +1 ms] Found plugin firexcode at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firexcode-1.0.5/
[   +6 ms] Found plugin flutter_plugin_android_lifecycle at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.1/
[  +13 ms] Found plugin image_editor_pro at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_editor_pro-1.1.8/
[   +2 ms] Found plugin image_picker at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.7.5/
[   +2 ms] Found plugin image_picker_for_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.0.0/
[   +9 ms] Found plugin package_info_plus at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus-1.0.1/
[   +3 ms] Found plugin package_info_plus_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus_macos-1.1.1/
[   +2 ms] Found plugin package_info_plus_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus_web-1.0.1/
[   +5 ms] Found plugin path_provider at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.2/
[   +1 ms] Found plugin path_provider_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +1 ms] Found plugin path_provider_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +2 ms] Found plugin path_provider_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.1/
[   +3 ms] Found plugin permission_handler at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/
[  +12 ms] Found plugin share_plus at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus-2.1.2/
[   +3 ms] Found plugin share_plus_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus_macos-2.0.2/
[   +4 ms] Found plugin share_plus_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus_web-2.0.4/
[   +4 ms] Found plugin shared_preferences at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.5/
[   +1 ms] Found plugin shared_preferences_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
[   +1 ms] Found plugin shared_preferences_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
[   +3 ms] Found plugin shared_preferences_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
[   +2 ms] Found plugin shared_preferences_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
[  +11 ms] Found plugin url_launcher at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.4/
[   +1 ms] Found plugin url_launcher_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.0/
[   +1 ms] Found plugin url_launcher_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.0/
[   +2 ms] Found plugin url_launcher_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.0/
[   +1 ms] Found plugin url_launcher_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.0/
[   +2 ms] Found plugin video_player at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-2.1.1/
[   +2 ms] Found plugin video_player_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_player_web-2.0.0/
[   +1 ms] Found plugin wakelock at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.5.2/
[   +1 ms] Found plugin wakelock_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_macos-0.1.0+1/
[   +2 ms] Found plugin wakelock_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_web-0.2.0+1/
[  +30 ms] Generating /root/parts/xifair-admin/build/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +175 ms] Building without sound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[  +30 ms] Building Linux application...
[  +41 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DFLUTTER_TARGET_PLATFORM=linux-x64
/root/parts/xifair-admin/build/linux
[ +832 ms] CMake Error: The current CMakeCache.txt directory /root/parts/xifair-admin/build/build/linux/x64/release/CMakeCache.txt is different than the
directory /home/joshua/dev/app/admin/build/linux/x64/release where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If
you are not sure, reedit the CMakeCache.txt
[   +9 ms] CMake Error: The source "/root/parts/xifair-admin/build/linux/CMakeLists.txt" does not match the source
"/home/joshua/dev/app/admin/linux/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
[  +95 ms] Building Linux application... (completed in 964ms)
[   +1 ms] "flutter linux" took 3,017ms.
[  +13 ms] Unable to generate build files
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runCmake (package:flutter_tools/src/linux/build_linux.dart:155:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:75:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:88:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +209 ms] ensureAnalyticsSent: 205ms
[   +4 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
Failed to run 'flutter build linux --release -v -t lib/main.dart' for 'xifair-admin': Exited with code 1.
Verify that the part is using the correct parameters and try again.
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
```
Any help?

**Comment by MarcusTomlinson** [comment]
Because you're using `source: .` in your `snapcraft.yaml`, snapcraft pulls in host build directory (with caches) into the snap. To fix this, you can either add:

```
override-pull: |
  set -eux
  rm -rf $SNAPCRAFT_PROJECT_DIR/build
  snapcraftctl pull
```

to the part with `source: .`, or just remove the `build` directory before running `snapcraft`.

**Comment by MarcusTomlinson** [comment]
@deut818 you could try setting your snap base to `core20` then adding `cmake` to your part's `build-packages`.

**Comment by MarcusTomlinson** [comment]
@drexhacker did you manage to come right with this?

**Comment by drexhacker** [comment]
I will try again though you can close the issue. Thank you

**Comment by tsinis** [comment]
> @deut818 you could try setting your snap base to `core20` then adding `cmake` to your part's `build-packages`.

`Failed to load extension 'flutter-stable': this extension does not support the 'core20' base.` :(
